name: API Linting

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git diff to work correctly
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      # Fetch the branch to compare changes
      - name: Fetch branch history
        run: git fetch --all

      # Get list of all changed YAML files in the pull request
      - name: List changed YAML files
        id: list_yaml_files
        run: |
          changed_files=$(git diff --name-only HEAD origin/dev | grep '\.yaml$')
          if [ -z "$changed_files" ]; then
            echo "No YAML files changed."
            exit 0
          fi
          echo "Changed YAML files:"
          echo "$changed_files"
          echo "::set-output name=files::$changed_files"

      # Run linting on each of the changed YAML files
      - name: Lint OpenAPI specification
        run: |
          for file in ${{ steps.list_yaml_files.outputs.files }}; do
            echo "Linting $file"
            redocly lint $file --config=.redocly.yaml --format=github-actions
          done
